# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatnik', '0003_auto_20171113_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Track Name')),
                ('artist', models.CharField(max_length=200, verbose_name='Artist Name')),
                ('album', models.CharField(max_length=200, verbose_name='Album Name')),
                ('apple_url', models.URLField(verbose_name='Apple Music URL')),
                ('gpm_url', models.URLField(verbose_name='Google Play Music URL')),
                ('spotify_url', models.URLField(verbose_name='Spotify URL')),
                ('soundcloud_url', models.URLField(verbose_name='Soundcloud URL')),
                ('match_rating', models.IntegerField(default=0, verbose_name='Rating of the match')),
                ('insertion_date', models.DateTimeField(verbose_name='Date of initial insertion')),
                ('update_date', models.DateTimeField(verbose_name='Date of last update')),
                ('artwork', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.RemoveField(
            model_name='album',
            name='apple_id',
        ),
        migrations.RemoveField(
            model_name='album',
            name='gpm_id',
        ),
        migrations.RemoveField(
            model_name='album',
            name='soundcloud_id',
        ),
        migrations.RemoveField(
            model_name='album',
            name='spotify_id',
        ),
        migrations.AddField(
            model_name='album',
            name='apple_url',
            field=models.URLField(default='', verbose_name='Apple Music URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='gpm_url',
            field=models.URLField(default='', verbose_name='Google Play Music URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='soundcloud_url',
            field=models.URLField(default='', verbose_name='Soundcloud URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='spotify_url',
            field=models.URLField(default='', verbose_name='Spotify URL'),
            preserve_default=False,
        ),
    ]
